config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/menu'

  get 'page/location'

  get 'page/outreach'

  root 'page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def menu
  end

  def location
  end

  def outreach
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="../../assets/peak.png" />
    <title>PEAK BREW</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
  </head>

  <body class="animated fadeIn">
    <%= yield %>
  </body>
</html>

app/views/page/home.html.erb
<div class="wrapper">
  <div class="topContainer">
    <img src="../../assets/deal.png" id="dealHome">
  </div>

  <div class="pageContainer">
    <div id="homeHeroContainer">
      <img id="logoHome" src="../../assets/logo.png" />
      <div id="pickerSection">
          <%= link_to image_tag("outreachButton.png", :class => "pagePicker animated jello"), page_outreach_path %>
          <%= link_to image_tag("locationButton.png", :class => "pagePicker animated jello"), page_location_path %>
          <%= link_to image_tag("menuButton.png", :class => "pagePicker animated jello"), page_menu_path %>
      </div>
    </div>
  </div>

  <footer>
    <div class="footerContainer">
      <div id="socialContainer">
        <img src="../../assets/facebook.png" class="socialIcon">
        <img src="../../assets/twitter.png" class="socialIcon">
        <img src="../../assets/insta.png" class="socialIcon">
      </div>
    </div>
  </footer>
</div>

app/views/page/location.html.erb
<div class="topContainer">
  <%= link_to image_tag("backButton.png", :class => "backButton animated jello"), root_path %>
</div>

<div class="pageContainer">
  <div id="mapContainer">
    <iframe
    width="300"
    height="300"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDVTURgnD0FkALiLzqAkYUvyhxyNwrfNU0&q=Mount+Fuji" allowfullscreen>
    </iframe>
    <div id="mapFooter">
      <p>
        That's right, we're located right at the peak of beautiful Mount Fuji!  <br />What, you thought our name was a joke?  Enjoy your climb, friend!
      </p>
    </div>
  </div>

</div>

<div class="footerContainer">
  <div id="socialContainer">
    <img src="../../assets/facebook.png" class="socialIcon">
    <img src="../../assets/twitter.png" class="socialIcon">
    <img src="../../assets/insta.png" class="socialIcon">
  </div>

</div>

app/views/page/menu.html.erb
<div class="topContainer">
  <%= link_to image_tag("backButton.png", :class => "backButton animated jello"), root_path %>
</div>

<div class="pageContainer">
  <div id="menuBox">
    <div id="menuTitle">
      <br />
      PEAK BREW <br />
      Menu Selection
      <hr />
    </div>
    <div class="menuColumn">
      House Blend - 2<br />
      Coffee on the Rocks - 3<br />
      Peak Secret - 4<br />
      Ultimate Coffee - 6<br />
    </div>
    <div class="menuColumn">
      Herbal Thunder - 4<br />
      Climber Special - 4<br />
      Cliffhanger - 4<br />
      Hiker's Nap - 4<br />
    </div>
    <div id="menuFooter">
      *All our products are gluten free, vegan, kid tested-mother approved, and whatever else pleases you hippies.
    </div>
  </div>
</div>

<div class="footerContainer">
  <div id="socialContainer">
    <img src="../../assets/facebook.png" class="socialIcon">
    <img src="../../assets/twitter.png" class="socialIcon">
    <img src="../../assets/insta.png" class="socialIcon">
  </div>
</div>

app/views/page/outreach.html.erb
<div class="topContainer">
  <%= link_to image_tag("backButton.png", :class => "backButton animated jello"), root_path %>
</div>

<div id="outreachPageContainer">
  <div id="outreachBox">
    <div id="outreachTitle">
      PEAK BREW
      Outreach Programs
      <hr />
    </div>
    <div class="outreachColumn">
      <div class="outreachColumnText">Nature Conservation
      </div><br />
      <%= image_tag("nature.jpg", :class => "outreachPic") %>
    </div>
    <div class="outreachColumn">
      <div class="outreachColumnText">Space Exploration
      </div><br />
      <%= image_tag("space.jpg", :class => "outreachPic") %>
    </div>
    <div class="outreachColumn">
      <div class="outreachColumnText">Youth
      </div><br />
      <%= image_tag("youth.jpg", :class => "outreachPic") %>
    </div>
  </div>
</div>

<div class="footerContainer">
  <div id="socialContainer">
    <img src="../../assets/facebook.png" class="socialIcon">
    <img src="../../assets/twitter.png" class="socialIcon">
    <img src="../../assets/insta.png" class="socialIcon">
  </div>
</div>